baseURL: http://vrcollab.com/
languageCode: en-us
title: VRcollab

params:
  MainCoverCarousel:
    - img/cover-bg.jpg
    - http://placehold.it/400x300
    - http://placehold.it/400x300
    - http://placehold.it/400x300
    - http://placehold.it/400x300
  SocialNetwork:
    Facebook: https://google.com
    Twitter: https://google.com
    YouTube: https://google.com
    LinkedIn: https://google.com
  MainGallery:
    - http://placehold.it/400x300
    - http://placehold.it/400x300
    - http://placehold.it/400x300
    - http://placehold.it/400x300
    - http://placehold.it/400x300
    - http://placehold.it/400x300
    - http://placehold.it/400x300
    - http://placehold.it/400x300

  Header:
    Product:
      - text: Lite
        url: "/lite"
      - text: Studio
        url: /studio
      - text: VR for AEC Proposal
        url: /vr-aec-proposal.pdf
    Learn:
      - text: Blog
        url: https://google.com
      - text: Helping Center
        url: https://google.com
      - text: FAQ
        url: https://google.com
  Footer:
    Product:
      - text: Login
        url: https://account.vrcollab.com
      - text: Lite
        url: "/lite"
      - text: Studio
        url: /studio
      - text: VR for AEC Proposal
        url: /vr-aec-proposal.pdf
    Learn:
      - text: Blog
        url: https://google.com
      - text: Helping Center
        url: https://google.com
      - text: FAQ
        url: https://google.com