baseURL: http://vrcollab.com/
languageCode: en-us
title: VRcollab

params:
  Header:
    Product:
      - text: Lite
        url: "/lite"
      - text: Studio
        url: /studio
      - text: VR for AEC Proposal
        url: /vr-aec-proposal.pdf
    Learn:
      - text: Blog
        url: https://google.com
      - text: Helping Center
        url: https://google.com
      - text: FAQ
        url: https://google.com
  Footer:
    Product:
      - text: Login
        url: https://account.vrcollab.com
      - text: Lite
        url: "/lite"
      - text: Studio
        url: /studio
      - text: VR for AEC Proposal
        url: /vr-aec-proposal.pdf
    Learn:
      - text: Blog
        url: https://google.com
      - text: Helping Center
        url: https://google.com
      - text: FAQ
        url: https://google.com