baseURL: http://vrcollab.com/
languageCode: en-us
title: VRcollab

params:
  MainCoverCarousel:
    - img/cover-bg.jpg
    - http://placehold.it/400x300
    - http://placehold.it/400x300
    - http://placehold.it/400x300
    - http://placehold.it/400x300
  SocialNetwork:
    Facebook: https://www.facebook.com/VRcollab/
    Twitter: https://twitter.com/vrcollab
    YouTube: https://www.youtube.com/channel/UCWrdTfVPQLrgeL-8tgbhhzg
    LinkedIn: https://www.linkedin.com/company/vrcollab/
  MainGallery:
    - http://placehold.it/400x300
    - http://placehold.it/400x300
    - http://placehold.it/400x300
    - http://placehold.it/400x300
    - http://placehold.it/400x300
    - http://placehold.it/400x300
    - http://placehold.it/400x300
    - http://placehold.it/400x300
  LiteGallery:
    - text: Measurements
      description: Accurate BIM measurements made with just a intuitive point and shoot motion.
      src: img/VRcollab LITE VDC Feature - Measurement.png
    - text: BIM Object Data
      description: Retrieve any element object data easily in both VR and desktop interfaces.
      src: img/VRcollab LITE VDC Feature - BIM Object Data.png
    - text: Annotations & Comments
      description: Markup an area with hand motions and use speech-to-text to tag an object for reiteration.
      src: img/VRcollab LITE VDC Feature - Annotation.png
    - text: Render Modes
      description: Switch render modes depending on the discussion for further design communication.
      src: img/VRCOLLAB LITE VDC Feature - Model View Modes.jpg
    - text: Merge BIM Models
      description: Combine models from multiple BIM software into a single VR interactive model.
      src: img/VRcollab LITE VDC Feature - Merge BIM Models.png
    - text: Desktop Friendly
      description: All features are that are available in VR are also enabled for mouse and keyboard usage.
      src: img/VRcollab LITE VDC Feature - Desktop Mode.jpg

  Header:
    Product:
      - text: Lite
        url: lite
      - text: Studio
        url: studio
      - text: VR for AEC Proposal
        url: vr-aec-proposal.pdf
    Learn:
      - text: Blog
        url: https://google.com
      - text: Helping Center
        url: https://google.com
      - text: FAQ
        url: https://google.com
      - text: About
        url: about
  Footer:
    Product:
      - text: Login
        url: https://account.vrcollab.com
      - text: Lite
        url: lite
      - text: Studio
        url: studio
      - text: VR for AEC Proposal
        url: /vr-aec-proposal.pdf
    Learn:
      - text: Blog
        url: https://google.com
      - text: Helping Center
        url: https://google.com
      - text: FAQ
        url: https://google.com
      - text: About
        url: about