baseURL: https://vrcollab.com/
languageCode: en-us
title: VRcollab
googleAnalytics: UA-124205822-1

params:
  Register: https://vrcollab.com/register
  Login: https://vrcollab.com/login
  MainCoverCarousel:
    - img/cover-bg.jpg
    - http://placehold.it/400x300
    - http://placehold.it/400x300
    - http://placehold.it/400x300
    - http://placehold.it/400x300
  Integration:
    - name: Revit
      src: img/revit-logo.png
    - name: SketchUp
      src: img/sketchup-logo.png
    - name: ArchiCAD
      src: img/archicad-logo.png
    - name: Navisworks
      src: img/navisworks-logo.png
    - name: HTC Vive
      src: img/htc-vive-logo.png
    - name: Mixed Reality
      src: img/windows-mixed-reality-logo.png
    - name: Oculus
      src: img/oculus-logo.png
  SocialNetwork:
    Facebook: https://www.facebook.com/VRcollab/
    Twitter: https://twitter.com/vrcollab
    YouTube: https://www.youtube.com/channel/UCWrdTfVPQLrgeL-8tgbhhzg
    LinkedIn: https://www.linkedin.com/company/vrcollab/
  Features:
    - text: Measurements
      description: Accurate BIM measurements made with just a intuitive point and shoot motion.
      src: img/VRcollab LITE VDC Feature - Measurement.png
    - text: Multi-User
      description: Coordinate BIM across the internet in Virtual Reality, up to 8 VR users at once.
      src: img/VRCOLLAB LITE VDC Feature - Cross Internet BIM Coordination.jpg
    - text: Daylight Analysis
      description: Set time of day and sun position in order to experience your building in dusk to dawn conditions.
      src: img/VRcollab LITE VDC Feature - Daylight Analysis.jpg
    - text: BIM Object Data
      description: Retrieve any element object data easily in both VR and desktop interfaces.
      src: img/VRcollab LITE VDC Feature - BIM Object Data.png
    - text: Annotations & Comments
      description: Markup an area with hand motions and use speech-to-text to tag an object for reiteration.
      src: img/VRcollab LITE VDC Feature - Annotation.png
    - text: Render Modes
      description: Switch render modes depending on the discussion for further design communication.
      src: img/VRCOLLAB LITE VDC Feature - Model View Modes.jpg
    - text: Merge BIM Models
      description: Combine models from multiple BIM software into a single VR interactive model.
      src: img/VRcollab LITE VDC Feature - Merge BIM Models.png
    - text: Desktop Friendly
      description: All features are that are available in VR are also enabled for mouse and keyboard usage.
      src: img/VRcollab LITE VDC Feature - Desktop Mode.jpg
  CaveGallery:
    - src: img/Renowned Architect Moshe Safdie using VRcollab Studio to review design.jpg
      text: Renowned Architect Moshe Safdie using VRcollab Studio to review design.
    - src: img/HDB VDC BIM Training Session.jpg
      text: VRcollab Studio setup in Housing and Development Board of Singapore.
    - src: img/Surbana Jurong using VRcollab for Live VDC Coordination.jpg
      text: Surbana Jurong using VRcollab for Live VDC Coordination.

  Header:
    Product:
      - text: Lite
        url: lite
      - text: Studio
        url: studio
      - text: VR for AEC Proposal
        url: VDC 2018 VRcollab AEC Proposal Deck.pdf
    Learn:
      - text: Blog
        url: https://blog.vrcollab.com
      - text: Helping Center
        url: https://help.vrcollab.com/
      - text: FAQ
        url: https://help.vrcollab.com/hc/en-us/sections/115000637574-5-General-FAQ
      - text: About
        url: about
  Footer:
    Product:
      - text: Login
        url: https://vrcollab.com/login
      - text: Lite
        url: lite
      - text: Studio
        url: studio
      - text: VR for AEC Proposal
        url: VDC 2018 VRcollab AEC Proposal Deck.pdf
    Learn:
      - text: Blog
        url: https://blog.vrcollab.com
      - text: Helping Center
        url: https://help.vrcollab.com/
      - text: FAQ
        url: https://help.vrcollab.com/hc/en-us/sections/115000637574-5-General-FAQ
      - text: About
        url: about